### ISSUE TITLE
Wrong tag for image in ceph-csi-rbd 2.0.0

### ISSUE THREAD

**Issue by eriklindahl** [ceph/csi-charts#1]
Line 107 of values.yaml for version 2.0.0 of the RBD chart (which specifies the tag for the cephcsi image) refers to "2.0.0", which I believe should be "v2.0.0".

This will cause all installations to fail, AFAIK.

**Comment by rootfs** [comment]
@Madhu-1

**Comment by Madhu-1** [comment]
@rootfs this is the mistake I did when we tagged for release in https://github.com/ceph/ceph-csi/pull/802/files#diff-f253394507ff98b71dde3817af2e4ccdR107, @eriklindahl can you set the `image.tag` to `v2.0.0` during installation
