### ISSUE TITLE
Allow to give the loglevel value --v arg

### ISSUE THREAD

**Issue by konvergence** [ceph/csi-charts#2]
Hi,

The chart actually fixe the arg "--v=5"  which but all logs  into trace level.
This generate a lot of logs.

Could you please templating the loglevel  "--v={{ .LogLevel }}" ?

It is ever done into the rook project: see https://github.com/rook/rook/commit/88b5d5ec3636ee56cab6f3ac454e077e451c1c12

Regards

**Comment by konvergence** [comment]
I pull the request on : https://github.com/ceph/csi-charts/pull/3

**Comment by rootfs** [comment]
please make changes against ceph/ceph-csi.
