### ISSUE TITLE
csi-snapshotter should be used with snapshot-controller

### ISSUE THREAD

**Issue by dashjay** [ceph/csi-charts#5]
There is only one csi-snapshotter in helm charts and it can only reconcile the `volumeSnapshotContent` and it nearly useless.

as [the design of snapshotter](https://github.com/kubernetes-csi/external-snapshotter#design)

> Both the snapshot [controller](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/controllers.md) and CSI external-snapshotter sidecar follow controller pattern and uses informers to watch for events. The snapshot controller watches for VolumeSnapshot and VolumeSnapshotContent create/update/delete events.
>
> The CSI external-snapshotter sidecar only watches for VolumeSnapshotContent create/update/delete events. It filters out these objects with Driver==<CSI driver name> specified in the associated VolumeSnapshotClass object and then processes these events in workqueues with exponential backoff.

> The CSI external-snapshotter sidecar talks to CSI over socket (/run/csi/socket by default, configurable by -csi-address).

after a certain version(I don't know it clearly), external-snapshotter split `cmd/csi-snapshotter` into`cmd/csi-snapshotter` and `cmd/snapshot-controller`

So shall we add one more container for `snapshot-controller`? or we have other considerations for not doing this.

**Comment by Madhu-1** [comment]
>Therefore, it is strongly recommended that Kubernetes distributors bundle and deploy the controller and CRDs as part of their Kubernetes cluster management process (independent of any CSI Driver).

>If your Kubernetes distribution does not bundle the snapshot controller, you may manually install these components by executing the following steps. Note that the snapshot controller YAML files in the git repository deploy into the default namespace for system testing purposes. For general use, update the snapshot controller YAMLs with an appropriate namespace prior to installing. For example, on a Vanilla Kubernetes cluster update the namespace from 'default' to 'kube-system' prior to issuing the kubectl create command.

We dont create snapshot-controller deployment as part of the csi charts it should be deployed by the kubernetes distributor, in cephcsi, we will deploy only the snapshot sidecar container which will act on the volumesnapshotcontent. if you still see any issue please open an issue at https://github.com/ceph/ceph-csi.
